name: Update Harga Telur DuckCare

on:
  workflow_dispatch:

  schedule:
    - cron: "17 0,6,12 * * *"

permissions:
  contents: write

jobs:
  update-egg-price:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install library Python
        run: |
          python -m pip install --upgrade pip
          pip install -r duckcare/bigdata/requirements.txt

      - name: Jalankan update harga telur
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGO_DB_NAME: harga_telur_db
          MONGO_COLLECTION: harga_harian
        run: |
          python duckcare/bigdata/update_egg_price.py

      - name: Commit report JSON terbaru
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add bigdata/output/report_harga_telur.json
          git diff --cached --quiet || git commit -m "Update report harga telur"
          git push
